<div class="col-md-8">
<div
    data-paginate-url="genres/paginate"
    data-offset="0"
    data-param=""
    class="playlists-container grid-container clearfix"
    id="genres-top">

    
	<?php foreach($C->model('admin')->getGenres() as $dgenre):?>
	
	
	
	<a data-ajax="true" href="<?php echo url('discover/genre/'.$dgenre['id'].'-'.toAscii($dgenre['name']))?>"  class="" style="flex: 0 0 20%;width: 20%;position: relative;padding: 30px 0px;overflow: hidden;display: inline-block;    float: left;border-radius: 5px;box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);    transition: all 0.2s;margin:2%;background: #FA0052 !important;color: #ffffff !important;
    border-color: #FA0052 !important;">
    <div style="position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    text-transform: capitalize;
    font-size: 15px;
    color: #ffffff;
    font-weight: 500;"><?php echo l($dgenre['name'])?></div></a>
                        
      <?php endforeach;?>
   
</div>
</div>

